/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronaldo
 */
public class PnlControlPagos extends javax.swing.JPanel {
    
    DefaultTableModel modeloTabla;

    /**
     * Creates new form PnlControlPagos
     */
    public PnlControlPagos() {
        initComponents();
        modeloTabla = new DefaultTableModel();
        // Crea las filas de las tablas.
        modeloTabla.addColumn("#");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Tiempo de aviso");
        modeloTabla.addColumn("Multa");
        modeloTabla.addColumn("Aviso de recargo");
        modeloTabla.addColumn("Pagos");
        this.tblControlPago.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblControlPago = new javax.swing.JTable();
        btnGenerarMulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbFiltro = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        tblControlPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "NOMBRE", "TIEMPO DE AVISO", "MULTA", "NOTIFICACION DE RECARGO", "PAGOS"
            }
        ));
        jScrollPane1.setViewportView(tblControlPago);

        btnGenerarMulta.setText("Generar multa");
        btnGenerarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMultaActionPerformed(evt);
            }
        });

        jLabel2.setText("CONTROL DE PAGOS");

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Todos", "Pago", "Deuda"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(600, 600, 600)
                        .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarMulta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarMulta)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarMultaActionPerformed

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    public JButton getBtnGenerarMulta() {
        return btnGenerarMulta;
    }

    public void setBtnGenerarMulta(JButton btnGenerarMulta) {
        this.btnGenerarMulta = btnGenerarMulta;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JComboBox<String> getJcbFiltro() {
        return jcbFiltro;
    }

    public void setJcbFiltro(JComboBox<String> jcbFiltro) {
        this.jcbFiltro = jcbFiltro;
    }

    public JTable getTblControlPago() {
        return tblControlPago;
    }

    public void setTblControlPago(JTable tblControlPago) {
        this.tblControlPago = tblControlPago;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarMulta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JTable tblControlPago;
    // End of variables declaration//GEN-END:variables
}
