package Vista;

/**
 * Este panel permite visualizar el estado de los pagos de todos los
 * propietarios además permite agregarles una multa en caso de que la fecha de
 * pago de su factura haya vencido.
 *
 * @author Grupo E
 */
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class PnlControlPagos extends javax.swing.JPanel {

    DefaultTableModel modeloTabla;

    public PnlControlPagos() {
        initComponents();
        modeloTabla = new DefaultTableModel();
        // Crea las filas de las tablas.
        modeloTabla.addColumn("#Cedula");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("F. Emision");
        modeloTabla.addColumn("F. Vencimiento");
        modeloTabla.addColumn("Pago");
        modeloTabla.addColumn("Multa");
        modeloTabla.addColumn("Recargo");
        modeloTabla.addColumn("Tipo Impuesto");
        this.tblControlPago.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarMulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblControlPago = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarMulta.setText("Generar multa");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Control de Pagos");

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Todos", "Pago", "Deuda"}));

        tblControlPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#CEDULA", "NOMBRE", "F. EMISION", "F. VENCIMIENTO", "PAGO ", "MULTA", "RECARGO", "TIPO IMPUESTO"
            }
        ));
        jScrollPane1.setViewportView(tblControlPago);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarMulta)
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(btnGenerarMulta)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    //getters and setters
    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    public JButton getBtnGenerarMulta() {
        return btnGenerarMulta;
    }

    public void setBtnGenerarMulta(JButton btnGenerarMulta) {
        this.btnGenerarMulta = btnGenerarMulta;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JComboBox<String> getJcbFiltro() {
        return jcbFiltro;
    }

    public void setJcbFiltro(JComboBox<String> jcbFiltro) {
        this.jcbFiltro = jcbFiltro;
    }

    public JTable getTblControlPago() {
        return tblControlPago;
    }

    public void setTblControlPago(JTable tblControlPago) {
        this.tblControlPago = tblControlPago;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarMulta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JTable tblControlPago;
    // End of variables declaration//GEN-END:variables
}
